modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/reap/issues"
[[mods]]
modId = "reap"
version = "${mod_version}"
displayName = "Reap Mod"
updateJSONURL = "https://update.maxhenkel.de/neoforge/reap"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/reap-mod"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''Harvest crops by right-clicking'''
[[dependencies.reap]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.reap]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"